Fix error[E0599]: `clone` the method `clone` exists for struct `Vec<PickTempData>`, but its trait bounds were not satisfied    --> src\lineup.rs:132:42     | 132 |                 let mut trial = starters.clone();     |                                          ^^^^^ method cannot     be called on `Vec<PickTempData>` due to unsatisfied trait bounds     |    ::: src\pick.rs:9:1